CREATE ROLE repuser WITH LOGIN REPLICATION PASSWORD 'rep_pass';
GRANT CONNECT ON DATABASE "TravelerDB" TO repuser;
GRANT USAGE ON SCHEMA public TO repuser;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO repuser;